name: Publish Parser to NuGet

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Package version (SemVer)"
        required: true

jobs:
  pack-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore workloads
        run: dotnet workload restore

      - name: Restore dependencies
        run: dotnet restore Protobuf.Decode.Parser/Protobuf.Decode.Parser.csproj

      - name: Build
        run: dotnet build Protobuf.Decode.Parser/Protobuf.Decode.Parser.csproj -c Release --no-restore

      - name: Pack
        run: dotnet pack Protobuf.Decode.Parser/Protobuf.Decode.Parser.csproj -c Release -p:PackageVersion=${{ github.event.inputs.version }} -o ./artifacts --no-build

      - name: Push to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "artifacts/Protobuf.Decode.Parser.${{ github.event.inputs.version }}.nupkg" --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate

