name: Publish to NuGet

on:
  push:
    tags:
      - 'v*.*.*'  # 触发条件：推送 v 开头的标签，如 v1.0.0
  workflow_dispatch:  # 允许手动触发

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore Protobuf.Decode.Parser/Protobuf.Decode.Parser.csproj
      
    - name: Build
      run: dotnet build Protobuf.Decode.Parser/Protobuf.Decode.Parser.csproj -c Release --no-restore
      
    - name: Extract version from tag
      id: get_version
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        else
          VERSION="1.0.0-dev.${{ github.run_number }}"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Package version: $VERSION"
        
    - name: Pack
      run: |
        dotnet pack Protobuf.Decode.Parser/Protobuf.Decode.Parser.csproj \
          -c Release \
          --no-build \
          -p:PackageVersion=${{ steps.get_version.outputs.VERSION }} \
          -p:PackageId=Protobuf.Decode.Parser \
          -p:Authors="wujun" \
          -p:Description="A lightweight Protobuf binary parser for .NET" \
          -p:PackageLicenseExpression=MIT \
          -p:PackageProjectUrl=https://github.com/yourusername/Protobuf.Decode \
          -p:RepositoryUrl=https://github.com/yourusername/Protobuf.Decode \
          -p:RepositoryType=git \
          -o ./artifacts
          
    - name: Publish to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: ./artifacts/*.nupkg

